# Generated by Django 5.2.5 on 2025-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_product_group_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('mobile', 'mobile')], default='mobile', max_length=20),
        ),
    ]
